### ISSUE TITLE
Reference to similar project

### ISSUE THREAD

**Issue by ugurdogrusoz** [aliatli/cs319group2b_CompletelyUnfair#1]
Is there a similar tool that you can cite, so we have a better understanding of what you're planning to do? If not, you should provide more details to what the input and output will be like.

**Comment by duhacelik** [comment]
Hocam, here is the similar program to ours:
https://www.youtube.com/watch?v=znWa7qKApcg

Basically, we are planning to do a simulation game that includes natural selection of the species in a random area and as a result of this, evolution.

Since we haven't decided the most of the project yet, we can't provide more details but if these information does not satisfy you we can try to be more spesific.

@ugurdogrusoz

**Comment by ugurdogrusoz** [comment]
Include these in your README please (Project Description page)
